# Generated by Django 3.2.20 on 2023-08-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios_likes', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscasamento',
            name='comentarios',
            field=models.ManyToManyField(blank=True, to='comentarios_likes.Comentarios'),
        ),
    ]
