# Generated by Django 3.2.20 on 2023-08-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curtir', '0001_initial'),
        ('core', '0002_fotoscasamento_comentarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscasamento',
            name='curtidas',
            field=models.ManyToManyField(blank=True, to='curtir.Curtidas'),
        ),
    ]
