# Generated by Django 3.2.20 on 2023-08-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fotoscasamento_curtidas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fotoscasamento',
            old_name='aprovar',
            new_name='aprovada',
        ),
    ]
