# Generated by Django 3.2.20 on 2023-08-24 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_aprovar_fotoscasamento_aprovada'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscasamento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_casamento'),
        ),
    ]
