# Generated by Django 4.2.4 on 2023-08-25 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fotoscasamento_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotoscasamento',
            name='quatidade_de_curtidas',
            field=models.IntegerField(default=0),
        ),
    ]
